In [33]:
import pandas as pd
import numpy as np

In [34]:
df = pd.read_csv('data.csv')

In [35]:
df = df[['name', 'category', 'foodCategory', 'Ingredient__ingredient']]
df.rename(columns = {'Ingredient__ingredient':'ingredient'}, inplace = True)

In [36]:
df['value'] = 1

In [37]:
df

name  category  foodCategory    ingredient  value
0   Chicken Broast         1             1  garam masala      1
1   Chicken Broast         1             1       chicken      1
2   Chicken Broast         1             1          salt      1
3   Chicken Broast         1             1           oil      1
4   Chicken Broast         1             1  green chilli      1
..             ...       ...           ...           ...    ...
67   Zinger Burger         3             1  Chees slices      1
68   Zinger Burger         3             1     Hot sauce      1
69   Zinger Burger         3             1    mayonnaise      1
70   Zinger Burger         3             1          milk      1
71   Zinger Burger         3             1           bun      1

[72 rows x 5 columns]

In [38]:
df = np.round(pd.pivot_table(df, values='value',
                                index=['name', 'category', 'foodCategory'], 
                                columns= 'ingredient', 
                                aggfunc=np.mean,
                                fill_value=0),2)

In [39]:
df

ingredient                            Baking powder  Chees slices  Cornflour  \
name           category foodCategory                                           
Chicken Broast 1        1                         0             0          0   
               3        1                         0             0          0   
Pizza          1        1                         0             0          0   
               3        1                         0             0          0   
Zinger Burger  1        1                         1             1          1   
               3        1                         1             1          1   

ingredient                            Hot sauce  Mustard powder  bun  butter  \
name           category foodCategory                                           
Chicken Broast 1        1                     0               0    0       0   
               3        1                     0               0    0       0   
Pizza          1        1                     0               0    0       1   
               3        1                     0               0    0       1   
Zinger Burger  1        1                     1               1    1       0   
               3        1                     1               1    1       0   

ingredient                            chicken  egg  flour  ...  oil  onion  \
name           category foodCategory                       ...               
Chicken Broast 1        1                   1    1      0  ...    1      0   
               3        1                   1    1      0  ...    1      0   
Pizza          1        1                   1    0      1  ...    1      1   
               3        1                   1    0      1  ...    1      1   
Zinger Burger  1        1                   1    1      1  ...    1      0   
               3        1                   1    1      1  ...    1      0   

ingredient                            oregano  red chili  salt  spice powders  \
name           category foodCategory                                            
Chicken Broast 1        1                   0          0     1              0   
               3        1                   0          0     1              0   
Pizza          1        1                   1          1     1              1   
               3        1                   1          1     1              1   
Zinger Burger  1        1                   0          0     1              0   
               3        1                   0          0     1              0   

ingredient                            sugar  tomato  water  yeast  
name           category foodCategory                               
Chicken Broast 1        1                 0       0      0      0  
               3        1                 0       0      0      0  
Pizza          1        1                 1       1      1      1  
               3        1                 1       1      1      1  
Zinger Burger  1        1                 1       0      0      0  
               3        1                 1       0      0      0  

[6 rows x 27 columns]

In [40]:
df.reset_index(inplace=True)

In [41]:
df

ingredient            name  category  foodCategory  Baking powder  \
0           Chicken Broast         1             1              0   
1           Chicken Broast         3             1              0   
2                    Pizza         1             1              0   
3                    Pizza         3             1              0   
4            Zinger Burger         1             1              1   
5            Zinger Burger         3             1              1   

ingredient  Chees slices  Cornflour  Hot sauce  Mustard powder  bun  butter  \
0                      0          0          0               0    0       0   
1                      0          0          0               0    0       0   
2                      0          0          0               0    0       1   
3                      0          0          0               0    0       1   
4                      1          1          1               1    1       0   
5                      1          1          1               1    1       0   

ingredient  ...  oil  onion  oregano  red chili  salt  spice powders  sugar  \
0           ...    1      0        0          0     1              0      0   
1           ...    1      0        0          0     1              0      0   
2           ...    1      1        1          1     1              1      1   
3           ...    1      1        1          1     1              1      1   
4           ...    1      0        0          0     1              0      1   
5           ...    1      0        0          0     1              0      1   

ingredient  tomato  water  yeast  
0                0      0      0  
1                0      0      0  
2                1      1      1  
3                1      1      1  
4                0      0      0  
5                0      0      0  

[6 rows x 30 columns]

In [42]:
print(df.columns.name)

ingredient


In [43]:
df.columns.name = None

In [44]:
df

name  category  foodCategory  Baking powder  Chees slices  \
0  Chicken Broast         1             1              0             0   
1  Chicken Broast         3             1              0             0   
2           Pizza         1             1              0             0   
3           Pizza         3             1              0             0   
4   Zinger Burger         1             1              1             1   
5   Zinger Burger         3             1              1             1   

   Cornflour  Hot sauce  Mustard powder  bun  butter  ...  oil  onion  \
0          0          0               0    0       0  ...    1      0   
1          0          0               0    0       0  ...    1      0   
2          0          0               0    0       1  ...    1      1   
3          0          0               0    0       1  ...    1      1   
4          1          1               1    1       0  ...    1      0   
5          1          1               1    1       0  ...    1      0   

   oregano  red chili  salt  spice powders  sugar  tomato  water  yeast  
0        0          0     1              0      0       0      0      0  
1        0          0     1              0      0       0      0      0  
2        1          1     1              1      1       1      1      1  
3        1          1     1              1      1       1      1      1  
4        0          0     1              0      1       0      0      0  
5        0          0     1              0      1       0      0      0  

[6 rows x 30 columns]

In [45]:
X = df.loc[:, df.columns!='name']
y = df["name"]

In [54]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
 
# clf = DecisionTreeClassifier()
clf = RandomForestClassifier(max_depth=10, random_state=0)
# Train Decision Tree Classifer
clf = clf.fit(X,y)

In [55]:
X.iloc[1].values

array([3, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [64]:
clf.predict([X.iloc[0].values])

c:\Users\MustafaAli\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array(['Chicken Broast'], dtype=object)

In [65]:
clf.feature_names_in_

array(['category', 'foodCategory', 'Baking powder', 'Chees slices',
       'Cornflour', 'Hot sauce', 'Mustard powder', 'bun', 'butter',
       'chicken', 'egg', 'flour', 'garam masala', 'garlic', 'ginger',
       'green chilli', 'mayonnaise', 'milk', 'mozzarella cheese', 'oil',
       'onion', 'oregano', 'red chili', 'salt', 'spice powders', 'sugar',
       'tomato', 'water', 'yeast'], dtype=object)

In [66]:
import pickle

filename = 'finalized_model.sav'
pickle.dump(clf, open(filename, 'wb'))

In [67]:
loaded_model = pickle.load(open("finalized_model.sav", 'rb'))
loaded_model.predict([[3, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0]])[0]

c:\Users\MustafaAli\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


'Chicken Broast'

In [76]:
probLst = loaded_model.predict_proba([X.iloc[0].values])[0]
probLst

c:\Users\MustafaAli\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0.87, 0.04, 0.09])

In [77]:
classIdxs = sorted(
    range(len(probLst)),
    key=lambda index: probLst[index]
)
classIdxs

[1, 2, 0]

In [71]:
loaded_model.feature_names_in_

array(['category', 'foodCategory', 'Baking powder', 'Chees slices',
       'Cornflour', 'Hot sauce', 'Mustard powder', 'bun', 'butter',
       'chicken', 'egg', 'flour', 'garam masala', 'garlic', 'ginger',
       'green chilli', 'mayonnaise', 'milk', 'mozzarella cheese', 'oil',
       'onion', 'oregano', 'red chili', 'salt', 'spice powders', 'sugar',
       'tomato', 'water', 'yeast'], dtype=object)

In [72]:
loaded_model.feature_importances_

array([0.0130303 , 0.        , 0.02893939, 0.06939394, 0.00909091,
       0.03606061, 0.03427273, 0.04772727, 0.05272727, 0.        ,
       0.04818182, 0.0619697 , 0.02969697, 0.04042424, 0.04      ,
       0.04409091, 0.06693939, 0.04787879, 0.04818182, 0.        ,
       0.03927273, 0.01590909, 0.04015152, 0.        , 0.02833333,
       0.05742424, 0.02863636, 0.03409091, 0.03757576])

In [73]:
loaded_model.classes_

array(['Chicken Broast', 'Pizza', 'Zinger Burger'], dtype=object)

In [78]:
predictClasses = [loaded_model.classes_[i] for i in classIdxs]
predictClasses


['Pizza', 'Zinger Burger', 'Chicken Broast']